#! /bin/sh
# start keybinds
sxhkd &
# start notif server
dunst &
# start polybar
polybar -r PolybarBot &

# bspc settings
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# bspwc monitor DP-1 -d 1 2 3 4
# bspwc montir HDMI1 -d 5 6 7 8

bspc config focus_follows_pointer   true
bspc config click_to_focus          button1
bspc config pointer_modifier        mod1
bspc config pointer_action1            move
bspc config pointer_action2         resize_corner

bspc config border_width            1
bspc config border_radius           2.5
bspc config window_gap              3
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# open console
urxvt &
# enable touchpad tap
xinput set-prop 14 305 1 &
# disable tap drag
xinput set-prop 14 307 0 &
# set wallpaper
feh --bg-fill /home/furry/Desktop/Files/Images/Wallpapers/firewatch_purple.jpg &
# open firefox + discord
firefox & discord
# gifWallpaper 0.05 /home/furry/Desktop/Files/Images/Download/ononokiyotsugi.gif
