hl.on("hyprland.start", function()
    hl.exec_cmd("~/.azotebg-hyprland")
    hl.exec_cmd("kitty")
    hl.exec_cmd("waybar")
    hl.exec_cmd("firefox")
    hl.exec_cmd("discord --enable-features=UseOzonePlatform --ozone-platform=wayland")
    hl.exec_cmd("swaync")
    hl.exec_cmd("otd-daemon")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
