-- Generated by nwg-displays on 2026-05-18 at 21:20:55. Do not edit manually.

hl.monitor({
    output = "desc:Microstep G274QPF E2 CC2HS85701472",
    mode = "2560x1440@180.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:NEC Corporation EA241F 44D03569NW",
    mode = "1920x1080@60.0",
    position = "2560x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:LG Electronics LG TV SSCR2 0x01010101",
    disabled = true
})
