-- Generated by nwg-displays on 2026-05-18 at 21:20:54. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:Microstep G274QPF E2 CC2HS85701472",
    default = true
})
hl.workspace_rule({
    workspace = "10",
    monitor = "desc:NEC Corporation EA241F 44D03569NW",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Microstep G274QPF E2 CC2HS85701472"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:Microstep G274QPF E2 CC2HS85701472"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "desc:Microstep G274QPF E2 CC2HS85701472"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "desc:Microstep G274QPF E2 CC2HS85701472"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "desc:Microstep G274QPF E2 CC2HS85701472"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "desc:Microstep G274QPF E2 CC2HS85701472"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "desc:Microstep G274QPF E2 CC2HS85701472"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "desc:NEC Corporation EA241F 44D03569NW"
})
